const quotes = {
    romance: [
        { quote: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle" },
        { quote: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
        { quote: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
        { quote: "As you wish.", author: "The Princess Bride (Film)" },
        { quote: "I love you not because of who you are, but because of who I am when I am with you.", author: "Nobita (Doraemon)" },
        { quote: "You are my sun, my moon, and all my stars.", author: "E.E. Cummings" },
        { quote: "To be your friend was all I ever wanted; to be your lover was all I ever dreamed.", author: "Valerie Lombardo" },
        { quote: "If I had a flower for every time I thought of you... I could walk through my garden forever.", author: "Alfred Tennyson" },
        { quote: "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.", author: "Angelita Lim" },
        { quote: "I am who I am because of you. You are every reason, every hope, and every dream I've ever had.", author: "Nicholas Sparks" },
        { quote: "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds.", author: "Nicholas Sparks, The Notebook" },
        { quote: "I need you like a heart needs a beat.", author: "One Republic" },
        { quote: "If I know what love is, it is because of you.", author: "Hermann Hesse" },
        { quote: "We are shaped and fashioned by what we love.", author: "Johann Wolfgang von Goethe" },
        { quote: "True love is rare, and it's the only thing that gives life real meaning.", author: "Nicholas Sparks" },
        { quote: "In your smile, I see something more beautiful than the stars.", author: "Beth Revis" },
        { quote: "Love is not only something you feel, it is something you do.", author: "David Wilkerson" },
        { quote: "To love is nothing. To be loved is something. But to love and be loved, that’s everything.", author: "T. Tolis" },
        { quote: "Love is the bridge between two hearts.", author: "Unknown" },
        { quote: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
        { quote: "You don't marry someone you can live with — you marry someone you cannot live without.", author: "Unknown" },
        { quote: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
        { quote: "Love is a friendship set to music.", author: "Joseph Campbell" },
        { quote: "You are the source of my joy, the center of my world and the whole of my heart.", author: "Unknown" },
        { quote: "I swear I couldn’t love you more than I do right now, and yet I know I will tomorrow.", author: "Leo Christopher" },
        { quote: "There is a madness in loving you, a lack of reason that makes it feel so flawless.", author: "Leo Christopher" },
        { quote: "You know you’re in love when you don’t want to fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
        { quote: "We are most alive when we're in love.", author: "John Updike" },
        { quote: "The way to love anything is to realize that it may be lost.", author: "G.K. Chesterton" },
        { quote: "Love is the ultimate expression of the will to live.", author: "Tom Wolfe" },
        // Anime Quotes
        { quote: "If you love someone, you protect them from the pain. You don’t become the cause of it.", author: "Natsuki Subaru (Re:Zero)" },
        { quote: "I always thought that life was about standing your ground, no matter how strong the current was.", author: "Takaki Tōno (5 Centimeters per Second)" },
        { quote: "The two of us aren't so different. My whole life I've desired from others. I felt bitter to the people who have what I don't.", author: "Shouya Ishida (A Silent Voice)" },
        { quote: "I really love you. More than anyone else in this world.", author: "Nagisa Furukawa (Clannad)" },
        { quote: "Love is like a mirror that reflects your bad side. Especially when it’s unrequited.", author: "Ultear Milkovich (Fairy Tail)" },
        { quote: "I'll make you so in love with me, that every time our lips touch, you'll die a little death.", author: "Ai Yazawa (Nana)" },
        { quote: "Even if I lose this feeling, I’m sure that I’ll just fall in love with you all over again.", author: "Syaoran Li (Cardcaptor Sakura)" },
        { quote: "Perhaps it's impossible to wear an identity without becoming what you pretend to be.", author: "Endo Kenji (Paranoia Agent)" },
        { quote: "If it's possible for one person to be hurt by another, then it's possible for that person to be healed by another.", author: "Sohma Hatori (Fruits Basket)" },
        { quote: "No matter how much we fight, the bond between us can't be broken.", author: "Haruhi Fujioka (Ouran High School Host Club)" },
        { quote: "The moment you find the courage to give up your life for someone... would be the moment you understand love.", author: "Kenshin Himura (Rurouni Kenshin)" },
        { quote: "If you love someone, you have to be prepared to set them free.", author: "Masami Kondou (After the Rain)" },
        { quote: "Love is never as simple as sharing the same path.", author: "Kaoru Kamiya (Rurouni Kenshin)" },
        { quote: "Even if we're apart, I'll always be with you.", author: "Mikasa Ackerman (Attack on Titan)" },
        { quote: "It's not that you can fall in love with someone new because you forgot the old. It's because you fall in love with someone new that you're able to forget about the old.", author: "Dr. Tenma (Monster)" },
        { quote: "I'd rather trust and regret than doubt and regret.", author: "Kirito (Sword Art Online)" }
    ],
    life: [
        { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
        { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
        { quote: "Carpe diem. Seize the day, boys.", author: "Dead Poets Society (Film)" },
        { quote: "Life is not a game of luck. If you wanna win, work hard.", author: "Sora (No Game No Life)" },
        { quote: "The unexamined life is not worth living.", author: "Socrates" },
        { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { quote: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
        { quote: "Life would be tragic if it weren't funny.", author: "Stephen Hawking" },
        { quote: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
        { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
        { quote: "Life is short, and it is here to be lived.", author: "Kate Winslet" },
        { quote: "Life is ten percent what happens to us and ninety percent how we respond to it.", author: "Charles R. Swindoll" },
        { quote: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
        { quote: "The purpose of life is to believe, to hope, and to strive.", author: "Indira Gandhi" },
        { quote: "Keep calm and carry on.", author: "Winston Churchill" },
        { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
        { quote: "When you cease to dream you cease to live.", author: "Malcolm Forbes" },
        { quote: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
        { quote: "The best things in life are free. The second best things are very, very expensive.", author: "Coco Chanel" },
        { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { quote: "Life is a series of natural and spontaneous changes. Don't resist them - that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like.", author: "Lao Tzu" },
        { quote: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
        { quote: "Life is a journey that must be traveled no matter how bad the roads and accommodations.", author: "Oliver Goldsmith" },
        { quote: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe" },
        { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
        { quote: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
        { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
        { quote: "Believe that life is worth living and your belief will help create the fact.", author: "William James" },
        // Anime Quotes
        { quote: "If you don’t take risks, you can’t create a future!", author: "Monkey D. Luffy (One Piece)" },
        { quote: "People’s lives don’t end when they die, it ends when they lose faith.", author: "Itachi Uchiha (Naruto)" },
        { quote: "To know sorrow is not terrifying. What is terrifying is to know you can’t go back to happiness you could have.", author: "Matsumoto Rangiku (Bleach)" },
        { quote: "When you give up, that’s when the game ends.", author: "Mitsuyoshi Anzai (Slam Dunk)" },
        { quote: "Fear is not evil. It tells you what your weakness is.", author: "Gildarts Clive (Fairy Tail)" },
        { quote: "If you don’t share someone’s pain, you can never understand them.", author: "Nagato (Naruto)" },
        { quote: "We are all like fireworks: we climb, we shine and always go our separate ways and become further apart. But even when that time comes, let’s not disappear like a firework, and continue to shine... forever.", author: "Hitsugaya Toshiro (Bleach)" },
        { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Brook (One Piece)" },
        { quote: "To forgive is to set a prisoner free and discover that the prisoner was you.", author: "Hinata Miyake (A Place Further than the Universe)" },
        { quote: "Sometimes, we have to look beyond what we want and do what’s best.", author: "Piccolo (Dragon Ball Z)" },
        { quote: "If you can’t do something, then don’t. Focus on what you can do.", author: "Shiroe (Log Horizon)" },
        { quote: "It's not the face that makes someone a monster; it's the choices they make with their lives.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "Hard work is worthless for those that don’t believe in themselves.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku (Dragon Ball Z)" },
        { quote: "It’s not the face that makes someone a monster; it’s the choices they make with their lives.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something.", author: "Edward Elric (Fullmetal Alchemist: Brotherhood)" },
        { quote: "If you can’t find a reason to fight, then you shouldn’t be fighting.", author: "Akame (Akame Ga Kill)" },
        { quote: "It’s not the face that makes someone a monster; it’s the choices they make with their lives.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "A place where someone still thinks about you is a place you can call home.", author: "Jiraiya (Naruto)" },
        { quote: "It's more important to master the cards you're holding than to complain about the ones your opponent was dealt.", author: "Grimsley (Pokemon)" }
    ],
    inspiration: [
        { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
        { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
        { quote: "Do, or do not. There is no try.", author: "Yoda (Star Wars)" },
        { quote: "Believe in yourself and create your own destiny. Don't fear failure.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
        { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
        { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
        { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
        { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
        { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
        { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
        { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { quote: "I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’", author: "Leah Busque" },
        { quote: "If people are doubting how far you can go, go so far that you can’t hear them anymore.", author: "Michele Ruiz" },
        { quote: "We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.", author: "Arianna Huffington" },
        { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
        { quote: "If you want to achieve greatness stop asking for permission.", author: "Unknown" },
        { quote: "Great things never come from comfort zones.", author: "Unknown" },
        { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
        { quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
        { quote: "The ones who are crazy enough to think they can change the world, are the ones that do.", author: "Anonymous" },
        { quote: "Don’t wait for opportunity. Create it.", author: "Anonymous" },
        { quote: "Be a positive energy trampoline – absorb what you need and rebound more back.", author: "Dave Carolan" },
        { quote: "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too.", author: "Mark Twain" },
        { quote: "When you’ve exhausted all possibilities, remember this: you haven’t.", author: "Thomas Edison" },
        { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
        { quote: "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.", author: "Michael Phelps" },
        // Anime Quotes
        { quote: "Don’t give up, there’s no shame in falling down! True shame is to not stand up again!", author: "Shintarō Midorima (Kuroko’s Basketball)" },
        { quote: "You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.", author: "Ging Freecss (Hunter x Hunter)" },
        { quote: "If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.", author: "Naruto Uzumaki (Naruto)" },
        { quote: "No matter how deep the night, it always turns to day, eventually.", author: "Brook (One Piece)" },
        { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel (Fairy Tail)" },
        { quote: "A person grows up when he's able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.", author: "Jiraiya (Naruto)" },
        { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel (Fairy Tail)" },
        { quote: "Power comes in response to a need, not a desire. You have to create that need.", author: "Goku (Dragon Ball Z)" },
        { quote: "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something.", author: "Edward Elric (Fullmetal Alchemist: Brotherhood)" },
        { quote: "If you can’t find a reason to fight, then you shouldn’t be fighting.", author: "Akame (Akame Ga Kill)" },
        { quote: "You need to accept the fact that you're not the best and have all the will to strive to be better than anyone you face.", author: "Roronoa Zoro (One Piece)" },
        { quote: "It’s more important to master the cards you’re holding than to complain about the ones your opponent was dealt.", author: "Grimsley (Pokémon)" },
        { quote: "A dropout will beat a genius through hard work.", author: "Rock Lee (Naruto)" },
        { quote: "Push through the pain, giving up hurts more.", author: "Vegeta (Dragon Ball Z)" },
        { quote: "You should enjoy the little detours. To the fullest. Because that’s where you’ll find the things more important than what you want.", author: "Ging Freecss (Hunter x Hunter)" },
        { quote: "If you don’t share someone’s pain, you can never understand them.", author: "Nagato (Naruto)" },
        { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel (Fairy Tail)" },
        { quote: "It’s more important to master the cards you’re holding than to complain about the ones your opponent was dealt.", author: "Grimsley (Pokémon)" },
        { quote: "We are all like fireworks: we climb, we shine and always go our separate ways and become further apart. But even when that time comes, let’s not disappear like a firework, and continue to shine... forever.", author: "Hitsugaya Toshiro (Bleach)" },
        { quote: "A person grows up when he's able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.", author: "Jiraiya (Naruto)" }
    ],
    wisdom: [
        { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
        { quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
        { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
        { quote: "With great power comes great responsibility.", author: "Spider-Man (Film)" },
        { quote: "The moment you think of giving up, think of the reason why you held on so long.", author: "Natsu Dragneel (Fairy Tail)" },
        { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
        { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
        { quote: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard" },
        { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
        { quote: "It is not how old you are, but how you are old.", author: "Jules Renard" },
        { quote: "The best way out is always through.", author: "Robert Frost" },
        { quote: "This above all: to thine own self be true.", author: "William Shakespeare" },
        { quote: "Life without love is like a tree without blossoms or fruit.", author: "Khalil Gibran" },
        { quote: "Wisdom is the reward you get for a lifetime of listening when you’d have preferred to talk.", author: "Doug Larson" },
        { quote: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
        { quote: "I was gratified to be able to answer promptly. I said, 'I don't know.'", author: "Mark Twain" },
        { quote: "Don't gain the world and lose your soul; wisdom is better than silver or gold.", author: "Bob Marley" },
        { quote: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
        { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
        { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
        { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
        { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
        { quote: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
        { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
        { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
        { quote: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
        { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
        { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
        { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" }
    ]
};

function generateQuote() {
    const theme = document.getElementById('theme').value;
    const selectedQuotes = quotes[theme];
    const randomIndex = Math.floor(Math.random() * selectedQuotes.length);
    const quote = selectedQuotes[randomIndex];

    document.getElementById('quote').innerText = `"${quote.quote}"`;
    document.getElementById('author').innerText = `- ${quote.author}`;
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('generate-btn').addEventListener('click', function() {
            document.getElementById('quote-box').style.display = 'block'; // Show the quote box
        });
    });
}
